import React,{useMemo,useState} from 'react';
import {Bot,Sparkles,FileText,CalendarDays,AlertTriangle,ArrowRight,Clock3,CheckCircle2,Send,X,ChevronRight,ReceiptText,BriefcaseBusiness,Package,ShieldCheck} from 'lucide-react';
import {useData} from './store.jsx';

const moneyNumber=v=>{const raw=String(v||'').replace(/[^0-9,.-]/g,'');const n=Number(raw.includes(',')?raw.replace(/\./g,'').replace(',','.'):raw);return Number.isFinite(n)?n:0};
const parseDate=v=>{const m=String(v||'').match(/(\d{1,2})\.(\d{1,2})\.(\d{4})/);return m?new Date(+m[3],+m[2]-1,+m[1]):new Date(v)};
function Pill({tone='blue',children}){return <span className={`ai-pill ${tone}`}>{children}</span>}
function DraftModal({draft,close}){const[text,setText]=useState(draft.body);return <div className="modal-backdrop" onMouseDown={close}><div className="modal ai-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="modal-kicker">NACRT NA OSNOVU PODATAKA</span><h2>{draft.title}</h2><p>Provjerite sadržaj prije korištenja.</p></div><button className="icon-btn" onClick={close}><X/></button></div><div className="ai-modal-body"><label>Sadržaj<textarea value={text} onChange={e=>setText(e.target.value)}/></label><div className="ai-disclaimer"><ShieldCheck/> Sistem ne šalje poruku bez vaše potvrde. Kopirajte provjereni sadržaj u željeni kanal.</div></div><div className="modal-actions"><button className="primary" onClick={()=>navigator.clipboard?.writeText(text)}><Send/> Kopiraj tekst</button></div></div></div>}
export default function AIAssistant(){
 const{jobs,offers,invoices,stock,maintenance,loading,error}=useData();const[tab,setTab]=useState('Pregled'),[prompt,setPrompt]=useState(''),[answer,setAnswer]=useState(''),[draft,setDraft]=useState(null);
 const now=new Date(),soon=new Date(Date.now()+7*86400000);
 const overdue=invoices.filter(i=>{const d=parseDate(i.due);return i.status!=='Plaćen'&&!isNaN(d)&&d<now});
 const expiring=offers.filter(o=>{const d=parseDate(o.valid);return !['Prihvaćena','Odbijena'].includes(o.status)&&!isNaN(d)&&d>=now&&d<=soon});
 const low=stock.filter(x=>(Number(x.stock)||0)<=(Number(x.min)||0));
 const dueMaintenance=maintenance.filter(x=>{const d=parseDate(x.next);return !isNaN(d)&&d>=now&&d<=soon});
 const openJobs=jobs.filter(j=>j.status!=='Završeno'),completed=jobs.filter(j=>j.status==='Završeno');
 const alerts=useMemo(()=>[
  ...(overdue.length?[{id:'overdue',title:`${overdue.length} računa kasni`,text:`Ukupno evidentirano: ${overdue.reduce((s,x)=>s+moneyNumber(x.amount),0).toFixed(2)} €`,type:'Naplata',tone:'red',icon:ReceiptText}]:[]),
  ...(expiring.length?[{id:'offers',title:`${expiring.length} ponuda uskoro ističe`,text:expiring.map(x=>x.no).filter(Boolean).join(', ')||'Provjerite rokove ponuda.',type:'Ponude',tone:'amber',icon:FileText}]:[]),
  ...(low.length?[{id:'stock',title:`${low.length} artikala ispod minimuma`,text:'Potrebno je planirati nabavku.',type:'Materijal',tone:'amber',icon:Package}]:[]),
  ...(dueMaintenance.length?[{id:'maintenance',title:`${dueMaintenance.length} održavanja dospijeva`,text:'Rok je u narednih sedam dana.',type:'Održavanje',tone:'blue',icon:BriefcaseBusiness}]:[])
 ],[invoices,offers,stock,maintenance]);
 const createDraft=a=>{if(a.id==='overdue'){const x=overdue[0];setDraft({title:`Podsjetnik za račun ${x?.no||''}`,body:`Poštovani ${x?.client||''},\n\nljubazno vas podsjećamo da račun ${x?.no||''} u iznosu ${x?.amount||''} nije evidentiran kao plaćen. Molimo provjerite status uplate.\n\nSrdačan pozdrav.`})}else if(a.id==='offers'){const x=expiring[0];setDraft({title:`Podsjetnik za ponudu ${x?.no||''}`,body:`Poštovani ${x?.client||''},\n\nponuda ${x?.no||''} uskoro ističe. Stojimo vam na raspolaganju za pitanja ili izmjene.\n\nSrdačan pozdrav.`})}};
 const ask=e=>{e.preventDefault();const q=prompt.toLowerCase();if(!q.trim())return;let a=`Trenutno imate ${openJobs.length} otvorenih poslova, ${overdue.length} računa koji kasne i ${low.length} artikala ispod minimuma.`;if(q.includes('prihod')||q.includes('naplat'))a=`Ukupno evidentirano kao plaćeno: ${invoices.reduce((s,x)=>s+moneyNumber(x.paid),0).toFixed(2)} €.`;if(q.includes('ponud'))a=`Imate ${offers.length} ponuda, od čega je ${offers.filter(x=>x.status==='Prihvaćena').length} prihvaćeno.`;if(q.includes('posao'))a=`Imate ${openJobs.length} otvorenih i ${completed.length} završenih poslova.`;setAnswer(a);setPrompt('')};
 if(loading)return <div className="card" style={{padding:30}}>Analiza stvarnih podataka...</div>;
 return <><div className="page-head ai-page-head"><div><p className="eyebrow">PAMETNI RADNI PROSTOR</p><h1>Poslovni pomoćnik</h1><p>Sažeci i upozorenja računaju se iz podataka vaše firme.</p></div><div className="ai-online"><i/> Podaci su ažurirani</div></div>{error&&<div className="schedule-warning"><AlertTriangle/>{error}</div>}
 <section className="ai-hero"><div className="ai-orb"><Bot/></div><div className="ai-hero-copy"><span>STVARNI PODACI</span><h2>Šta želite provjeriti?</h2><p>Pitajte za poslove, ponude, naplatu ili materijal.</p></div><form className="ai-prompt" onSubmit={ask}><Sparkles/><input value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Npr. koliko računa kasni?"/><button><Send/></button></form></section>
 {answer&&<section className="ai-answer"><div className="ai-answer-icon"><Bot/></div><div><strong>Odgovor iz baze</strong><p>{answer}</p></div><button className="icon-btn" onClick={()=>setAnswer('')}><X/></button></section>}
 <div className="ai-tabs">{['Pregled','Upozorenja'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}{t==='Upozorenja'&&<em>{alerts.length}</em>}</button>)}</div>
 <div className="ai-layout"><section className="card ai-alerts"><div className="card-head"><div><h3>Zahtijeva pažnju</h3><p>{alerts.length?`${alerts.length} stvarnih stavki za provjeru`:'Nema upozorenja prema trenutnim podacima'}</p></div>{tab==='Pregled'&&alerts.length>3&&<button onClick={()=>setTab('Upozorenja')}>Prikaži sve <ChevronRight/></button>}</div><div>{(tab==='Pregled'?alerts.slice(0,3):alerts).map(a=>{const Icon=a.icon;return <article className="ai-alert-row" key={a.id}><div className={`ai-alert-icon ${a.tone}`}><Icon/></div><div className="ai-alert-copy"><div><strong>{a.title}</strong><Pill tone={a.tone}>{a.type}</Pill></div><p>{a.text}</p></div>{['overdue','offers'].includes(a.id)&&<button onClick={()=>createDraft(a)}>Pripremi nacrt <ArrowRight/></button>}</article>})}{!alerts.length&&<div className="empty-row"><CheckCircle2/> Trenutno nema stavki koje zahtijevaju pažnju.</div>}</div></section>
 <aside className="card ai-summary"><div className="ai-summary-top"><Bot/><div><span>SAŽETAK IZ BAZE</span><strong>Pregled poslovanja</strong></div></div><ul><li><CheckCircle2/><span><strong>{completed.length} poslova</strong> završeno ukupno</span></li><li><AlertTriangle/><span><strong>{alerts.length} upozorenja</strong> zahtijeva pažnju</span></li><li><Clock3/><span><strong>{openJobs.length} poslova</strong> trenutno otvoreno</span></li></ul></aside></div>{draft&&<DraftModal draft={draft} close={()=>setDraft(null)}/>}</>
}
